# Just Run It:
#   cspell "**/*.md" --no-progress
# Run It focusing on most common issues:
#   cspell "**/*.md" --no-progress --quiet --reporter @cspell/cspell-json-reporter | jq -r '.issues[].text' | sort | uniq -c | sort -nr | head -5


# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en

dictionaries:
  - en_US
  - companies
  - markdown
  - softwareTerms
  - html
  - bash
  - powershell
  - filetypes
  # Custom Dictionaries
  - akeyless-standard
  - akeyless-proper-nouns

ignorePaths:
  - .cspell/**
  - .github/**
  - .other/**
  - .venv/**
  - recipes/**
  - reference/**
  - samples/**
  - .gitignore
  - cspell.config.yaml
  - docs/Contributing Guides/look-feel-sample-page-title.md
  - docs/Contributing Guides/technical-documentation-style-guide/index.md
  - docs/Contributing Guides/technical-documentation-style-guide/ai-linter-rules.md

dictionaryDefinitions:
  - name: akeyless-proper-nouns
    path: .cspell/akeyless-proper-nouns-dictionary.txt
    addWords: true
  - name: akeyless-standard
    path: .cspell/akeyless-standard-dictionary.txt
    addWords: true

overrides:
  - filename: "**/*.md"
    languageId: markdown
    ignoreRegExpList:
      - /`[^`]*`/
      - /```[\s\S]*?```/
      - /^\s*slug:\s*.*$/m # Ignore front-matter slug values
    words:
      - creds
      - sqlnet
      - cwallet
      - apiserver
      - apikey
      - pkitls
      - sourcetype
      - AkeylessCreds
      - amqps
      - dbname 

  # Allow PostgreSQL-specific term "usename" only in selected files.
  # Adjust the filename globs to match where you discuss or show pg_stat_activity / SQL revoke statements.
  - filename:
      - "docs/Integrations & Plugins/cli-reference/cli-reference-dynamic-secrets.md"
    words:
      - usename

  # "hanadb" and "dockerhub" are CLI subcommands
  - filename:
      - "docs/Integrations & Plugins/cli-reference/cli-reference-dynamic-secrets.md"
    words:
      - hanadb
      - dockerhub

  # "forwading" is a known issue: ASM-16564
  - filename:
      - "docs/Secure Remote Access/admin-guides/supported-resource-types/k8s-cluster-access.md"
      - "docs/Integrations & Plugins/cli-reference/cli-reference-dynamic-secrets.md"
    words:
      - forwading

  # "vaultless" is a parameter option
  - filename:
      - "docs/Integrations & Plugins/cli-reference/cli-reference-encryption-keys.md"
    words:
      - vaultless

  # "sumologic" is a parameter option
  - filename:
      - "docs/Akeyless Gateway/install-and-configure-the-gateway/gw-docker-log-forwarding.md"
    words:
      - sumologic

  # "sumologic" is a parameter option
  - filename:
      - "docs/Advanced Functionality/automatic-migration/index.md"
    words:
      - secretmanager
