name: CLI Command Path Check (Akeyless + kubectl) (Manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cli-path-check:
    uses: ./.github/workflows/reusable-cli-command-path-check.yml
    with:
      push_changes: true
      branch_name: automation/cli-command-path-check
    secrets: inherit
