name: Link Checker (Manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  link-check:
    uses: ./.github/workflows/reusable-link-check.yml
    with:
      push_changes: true
      branch_name: automation/link-check
    secrets: inherit
