name: Markdown Linter (Manual)

on:
  workflow_dispatch:

jobs:
  markdownlint:
    uses: ./.github/workflows/reusable-markdownlint.yml
    with:
      push_changes: true
      branch_name: automation/markdownlint
    secrets: inherit
