name: Spell Checker (Manual)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  spell-check:
    uses: ./.github/workflows/reusable-spell-check.yml
    with:
      push_changes: true
      branch_name: automation/spell-check
    secrets: inherit
